export type Taxes = {
  MAX_TAX_EFFICIENT_SALARY_PENCE: number;
  CORPORATION_TAX_PERCENTAGE: number;
  BASIC_DIVIDEND_TAX_RATE_PERCENTAGE: number;
  HIGHER_DIVIDEND_TAX_RATE_PERCENTAGE: number;
  ADDITIONAL_DIVIDEND_TAX_RATE_PERCENTAGE: number;
  DIVIDEND_TAX_FREE_ALLOWANCE_PENCE: number;
  HIGHER_DIVIDEND_TAX_THRESHOLD_PENCE: number;
  ADDITIONAL_DIVIDEND_TAX_THRESHOLD_PENCE: number;
  TAX_FREE_PERSONAL_ALLOWANCE_PENCE: number;
  MAXIMUM_FULL_PERSONAL_ALLOWANCE_THRESHOLD_PENCE: number;
};

export const TAXES: { [key: string]: Taxes } = {
  "2021/22": {
    MAX_TAX_EFFICIENT_SALARY_PENCE: 12564 * 100,
    CORPORATION_TAX_PERCENTAGE: 19,

    BASIC_DIVIDEND_TAX_RATE_PERCENTAGE: 7.5,
    HIGHER_DIVIDEND_TAX_RATE_PERCENTAGE: 32.5,
    ADDITIONAL_DIVIDEND_TAX_RATE_PERCENTAGE: 38.1,

    DIVIDEND_TAX_FREE_ALLOWANCE_PENCE: 2000 * 100,
    HIGHER_DIVIDEND_TAX_THRESHOLD_PENCE: 37700 * 100,
    ADDITIONAL_DIVIDEND_TAX_THRESHOLD_PENCE: 150000 * 100,

    TAX_FREE_PERSONAL_ALLOWANCE_PENCE: 12570 * 100,
    MAXIMUM_FULL_PERSONAL_ALLOWANCE_THRESHOLD_PENCE: 100000 * 100,
  },
  "2022/23": {
    MAX_TAX_EFFICIENT_SALARY_PENCE: 12564 * 100,
    CORPORATION_TAX_PERCENTAGE: 19,
    BASIC_DIVIDEND_TAX_RATE_PERCENTAGE: 8.75,
    HIGHER_DIVIDEND_TAX_RATE_PERCENTAGE: 33.75,
    ADDITIONAL_DIVIDEND_TAX_RATE_PERCENTAGE: 39.35,

    DIVIDEND_TAX_FREE_ALLOWANCE_PENCE: 2000 * 100,
    HIGHER_DIVIDEND_TAX_THRESHOLD_PENCE: 37700 * 100,
    ADDITIONAL_DIVIDEND_TAX_THRESHOLD_PENCE: 150000 * 100,

    TAX_FREE_PERSONAL_ALLOWANCE_PENCE: 12570 * 100,
    MAXIMUM_FULL_PERSONAL_ALLOWANCE_THRESHOLD_PENCE: 100000 * 100,
  },
  "2023/24": {
    MAX_TAX_EFFICIENT_SALARY_PENCE: 12564 * 100,
    CORPORATION_TAX_PERCENTAGE: 25,
    BASIC_DIVIDEND_TAX_RATE_PERCENTAGE: 8.75,
    HIGHER_DIVIDEND_TAX_RATE_PERCENTAGE: 33.75,
    ADDITIONAL_DIVIDEND_TAX_RATE_PERCENTAGE: 39.35,

    DIVIDEND_TAX_FREE_ALLOWANCE_PENCE: 2000 * 100,
    HIGHER_DIVIDEND_TAX_THRESHOLD_PENCE: 37700 * 100,
    ADDITIONAL_DIVIDEND_TAX_THRESHOLD_PENCE: 150000 * 100,

    TAX_FREE_PERSONAL_ALLOWANCE_PENCE: 12570 * 100,
    MAXIMUM_FULL_PERSONAL_ALLOWANCE_THRESHOLD_PENCE: 100000 * 100,
  },
  "2024/25": {
    MAX_TAX_EFFICIENT_SALARY_PENCE: 12564 * 100,
    CORPORATION_TAX_PERCENTAGE: 25,
    BASIC_DIVIDEND_TAX_RATE_PERCENTAGE: 8.75,
    HIGHER_DIVIDEND_TAX_RATE_PERCENTAGE: 33.75,
    ADDITIONAL_DIVIDEND_TAX_RATE_PERCENTAGE: 39.35,

    DIVIDEND_TAX_FREE_ALLOWANCE_PENCE: 2000 * 100,
    HIGHER_DIVIDEND_TAX_THRESHOLD_PENCE: 37700 * 100,
    ADDITIONAL_DIVIDEND_TAX_THRESHOLD_PENCE: 150000 * 100,

    TAX_FREE_PERSONAL_ALLOWANCE_PENCE: 12570 * 100,
    MAXIMUM_FULL_PERSONAL_ALLOWANCE_THRESHOLD_PENCE: 100000 * 100,
  },
};

// const UPPER_LIMIT = 250000;
// const PROFIT_MULTIPLIER = 0.25;
// const MARGINAL_RATE_MULTIPLIER = 3 / 200;

// const profit = 120000;
// // step 1
// const profitPlus25Percent = profit * PROFIT_MULTIPLIER;
// console.log("profitPlus25Percent", profitPlus25Percent);

// // step 3
// const marginalReleif = (UPPER_LIMIT - profit) * MARGINAL_RATE_MULTIPLIER;
// console.log("marginalReleif", marginalReleif);

// // step 4
// const taxDue = profitPlus25Percent - marginalReleif;
// console.log("taxDue should be 28,050.00", taxDue);
